apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: dev
namePrefix: dev-
commonLabels:
  environment: dev

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: awesome-app
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: dev.rancher.local

images:
  - name: ghcr.io/codayblue/kubernetes-workshop
    newTag: 1.0.0
