apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: prod
namePrefix: prod-
commonLabels:
  environment: prod

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: awesome-app
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: prod.rancher.local
  - path: deployment.yaml

images:
  - name: ghcr.io/codayblue/kubernetes-workshop/app
    newTag: 0.5.0