apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: awesome-app
  name: awesome-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awesome-app
  template:
    metadata:
      labels:
        app: awesome-app
    spec:
      containers:
      - image: ghcr.io/codayblue/kubernetes-workshop/app:latest
        imagePullPolicy: IfNotPresent
        name: app
        ports:
          - name: http
            containerPort: 80
        resources: {}
